-- Run this in the Supabase SQL Editor before using the public review form.
-- The anon role can submit only pending reviews; only authenticated users
-- listed in public.review_admins can moderate them.
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  rating integer not null check (rating between 1 and 5),
  message text not null check (char_length(message) between 1 and 2000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.reviews
  add column if not exists status text not null default 'pending';
alter table public.reviews
  add column if not exists reviewed_at timestamptz;

create table if not exists public.review_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.review_notifications (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  notification_type text not null default 'review_submitted',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists review_notifications_review_id_idx
  on public.review_notifications(review_id);
create index if not exists reviews_status_created_at_idx
  on public.reviews(status, created_at desc);

create or replace function public.create_review_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.review_notifications (review_id)
  values (new.id)
  on conflict (review_id) do nothing;
  return new;
end;
$$;

drop trigger if exists reviews_create_notification on public.reviews;
create trigger reviews_create_notification
  after insert on public.reviews
  for each row execute function public.create_review_notification();

alter table public.reviews enable row level security;
alter table public.review_admins enable row level security;
alter table public.review_notifications enable row level security;

revoke all on table public.reviews from anon, authenticated;
revoke all on table public.review_admins from anon, authenticated;
revoke all on table public.review_notifications from anon, authenticated;

grant usage, select on sequence public.reviews_id_seq to anon, authenticated;
grant insert on table public.reviews to anon;
grant select on table public.reviews to anon, authenticated;
grant update on table public.reviews to authenticated;
grant select on table public.review_admins to authenticated;
grant select, update on table public.review_notifications to authenticated;

drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can read approved reviews"
  on public.reviews
  for select
  to anon, authenticated
  using (status = 'approved');

drop policy if exists "Public can submit reviews" on public.reviews;
create policy "Public can submit reviews"
  on public.reviews
  for insert
  to anon
  with check (status = 'pending');

drop policy if exists "Review admins can read all reviews" on public.reviews;
create policy "Review admins can read all reviews"
  on public.reviews
  for select
  to authenticated
  using (exists (select 1 from public.review_admins where user_id = auth.uid()));

drop policy if exists "Review admins can update reviews" on public.reviews;
create policy "Review admins can update reviews"
  on public.reviews
  for update
  to authenticated
  using (exists (select 1 from public.review_admins where user_id = auth.uid()))
  with check (exists (select 1 from public.review_admins where user_id = auth.uid()));

drop policy if exists "Review admins can read their admin record" on public.review_admins;
create policy "Review admins can read their admin record"
  on public.review_admins
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Review admins can read notifications" on public.review_notifications;
create policy "Review admins can read notifications"
  on public.review_notifications
  for select
  to authenticated
  using (exists (select 1 from public.review_admins where user_id = auth.uid()));

drop policy if exists "Review admins can mark notifications read" on public.review_notifications;
create policy "Review admins can mark notifications read"
  on public.review_notifications
  for update
  to authenticated
  using (exists (select 1 from public.review_admins where user_id = auth.uid()))
  with check (exists (select 1 from public.review_admins where user_id = auth.uid()));

-- To grant moderation access, create an Auth user in Supabase, then run:
-- insert into public.review_admins (user_id)
-- values ('AUTH-USER-UUID-HERE');
